### PR TITLE
feat: Make API Key & networking optional

### PR DESCRIPTION
**Pull request by MSWagner**
Support for local language files:

- If the API Key is not included in icapps_translations config, the networking tasks will be skipped.

### CODE REVIEW

**Comment by vanlooverenkoen** [comment]
@MSWagner please take a look at https://pub.dev/packages/locale_gen this is a package I created that does the same thing

But indeed maybe we should merge them together to always have the latest fixes in both

I think it better to use locale_gen as the default package. And use that in this package

**Comment by MSWagner** [comment]
@vanlooverenkoen That would be a good solution. The tests in your template project failing with the locale_gen package

**Comment by vanlooverenkoen** [comment]
Hmm alright. I will try to do some fixes this week. And try to merge them together

**Comment by vanlooverenkoen** [comment]
Refactor is completed both packages are released:

locale_gen: 2.0.0
icapps_translations: 3.0.0

I think this makes this pr obsolete. Please create a new ticket on locale_gen if you have another issue. For now I will close this pull requests

**Pull request closed without merging**
